---
- include_tasks: unattended-upgrades.yml
- include_tasks: fail2ban.yml
- include_tasks: ssh.yml
- include_tasks: network_ubuntu.yml
  when: ansible_distribution is 'Ubuntu'
- include_tasks: users.yml
