---
- name: Network | static IP assignment
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
  notify:
  - restart system
  - wait for system restart

- name: Network | create VPN route table
  copy:
    dest: /etc/iproute2/rt_tables.d/vpn.conf
    content: '200 vlanvpn'

- name: Network | add VPN routes
  copy:
    dest: /lib/dhcpcd/dhcpcd-hooks/40-vpnroute
    content: |
      if [ "$interface" = "{{ vpn_vlan_interface }}" ]; then
        ip route add table vlanvpn default via {{ vpn_vlan_gateway }}
        ip rule add from {{ vpn_vlan_network }} lookup vlanvpn
      fi
  notify:
  - restart system
  - wait for system restart
