---
- name: Users | remove default user
  user:
    name: pi
    state: absent
    remove: yes

- name: Users | install mkpasswd 
  apt:
    name: whois
    state: present
    
- name: Users | create users
  include_tasks: add_user.yml
  loop: "{{ users }}"
  loop_control:
    label: "{{ _add_user.username }}"
    loop_var: _add_user
  when: not ansible_check_mode