---
- hosts: bastion
  become: true
  tasks:
  - include_role:
      name: bastion
    vars:
      interfaces: "{{ network_interfaces }}"
      vpn_vlan_gateway: "{{ network_vpn_vlan_gateway }}"
      vpn_vlan_network: "{{ network_vpn_vlan_network }}"

  - include_role:
      name: nfs_mount
    vars:
      mount_path: "{{ nfs_mount_path }}"
      source: "{{ nfs_source }}"
      options: "{{ nfs_options }}"

  - include_role:
      name: transmission
    vars:
      download_path: "{{ transmission_download }}"
      settings: "{{ transmission_settings }}"
