---
- hosts: bastion
  become: true
  tasks:
  - import_role:
      name: bastion
    vars:
      users: "{{ bastion_users }}"
      interfaces: "{{ network_interfaces }}"
      dns_servers: "{{ network_dns_servers }}"
      vpn_vlan_interface: "{{ network_vpn_vlan_interface }}"
      vpn_vlan_ipv4_gateway: "{{ network_vpn_vlan_ipv4_gateway }}"
      vpn_vlan_ipv4_network: "{{ network_vpn_vlan_ipv4_network }}"
    tags: [bastion]

  - import_role:
      name: cloudflared
    vars:
      service_suffix: dns
      service_config: "{{ cloudflare_dns_service_config }}"
    tags: [cloudflared,dnsproxy]

  - import_role:
      name: cloudflared
    vars:
      service_suffix: pihole
      service_config: "{{ cloudflare_pihole_service_config }}"
      service_systemd_after: cloudflared-dns.service
    tags: [cloudflared,argotunnel,argotunnel-pihole]

  - import_role:
      name: cloudflared
    vars:
      service_suffix: nas
      service_config: "{{ cloudflare_nas_service_config }}"
      service_systemd_after: cloudflared-dns.service
    tags: [cloudflared,argotunnel,argotunnel-nas]

  - import_role:
      name: cloudflared
    vars:
      service_suffix: plex
      service_config: "{{ cloudflare_plex_service_config }}"
      service_systemd_after: cloudflared-dns.service
    tags: [cloudflared,argotunnel,argotunnel-plex]

#  - import_role:
#      name: cloudflared
#    vars:
#      service_suffix: transmission
#      service_config: "{{ cloudflare_transmission_service_config }}"
#      service_systemd_after: cloudflared-dns.service
#    tags: [cloudflared,argotunnel,argotunnel-transmission]

  - import_role:
      name: cloudflared
    vars:
      service_suffix: freenas
      service_config: "{{ cloudflare_freenas_service_config }}"
      service_systemd_after: cloudflared-dns.service
    tags: [cloudflared,argotunnel,argotunnel-freenas]

  - import_role:
      name: nfs_mount
    vars:
      mount_path: "{{ nfs_mount_path }}"
      source: "{{ nfs_source }}"
      options: "{{ nfs_options }}"
    tags: [nfs]

  - import_role:
      name: transmission
    vars:
      download_path: "{{ transmission_download }}"
      settings: "{{ transmission_settings }}"
    tags: [transmission]