---
- name: update package cache
  apt:
    update_cache: yes

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
  - transmission-common
  - transmission-daemon
  - transmission-cli

- name: ensure download directory exists
  file:
    path: "{{ download_path }}"
    state: directory
    mode: 0775

- name: ensure service not running
  service:
    name: transmission-daemon
    state: stopped

- name: update config settings
  lineinfile:
    #path: /etc/transmission-daemon/settings.json
    path: /var/lib/transmission-daemon/info/settings.json
    regexp: '^(\s+"{{ item.key }}"):\s+"(.*)"(,?)$'
    line: '\1: "{{ item.value }}"\3'
    backrefs: yes
  loop: "{{ settings }}"

- name: create systemd override directory
  file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: override systemd service settings
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/transmission-daemon.service.d/override.conf
    owner: root
    group: root
  register: transmission_service

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: transmission_service.changed

- name: ensure service is running
  service:
    name: transmission-daemon
    state: started
