---
- name: ensure NFS client installed
  package:
    name: nfs-common
    state: latest

- name: ensure mount point exists
  file:
    path: "{{ nfs_mount_path }}"
    state: directory

- name: create mount
  mount:
    path: "{{ nfs_mount_path }}"
    src: "{{ nfs_source }}"
    fstype: nfs
    opts: "{{ nfs_options }}"
    state: mounted
