ansible_user: "{{ vault_provisioning_username }}"
ansible_become_pass: "{{ vault_provisioning_password }}"

bastion_users:
- username: mark
  password: "{{ vault_user_mark_password }}"
  shell: /bin/bash
  groups:
  - users
  - sudo
  authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6Tvl6E1eMdyvazTIRH3eA2qUqTn5lR7pVdWpQQeVT4sBxzN273XqPvxznmVBMxo0QSWYqLPWVLcygmUo/ZYcEOJBgpdDrX71km3iyEp07TMGJzpSJ6Ioy1HHK3P8G+XCESX6SxJS4XrD/IIM9MBL5yAjrjU8lmqQ5s4/y8LLzsTrPiSU3aFaFWRaRUmFSx07zq78pp+B+vVOvM4CC/uaASQbbIz+zfGlIDsOHXjUmYmZVpnHgQMbXldy+ftEGDwqZcFcJOqgEGEMe9+BILh24NuKq8jj6uHXlGw1hoXHn8FPUZ09yMnE5Z+PGgjWqDZa6BOxdcgo/I68l8Jj9pWRH mark@bakedbeans.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcQE/cTtzHHZ6c1R0ZwGGmebYQI4mzZcdAydfJR/MlQnjW1974tP7EDQ4lM0jL/PqNoePc2t/5TVuG7e+JR/SnJi4wpflRuCZPVyfnf5Q6z/gXPzzdeL15XYPlZJNRrZF5UCBMVR6u9+nMCOLp5uIrSGisBya40elTvxxWeTbmhheXwlUgRFFqujgDm69LaqgQMfctrbjGqbMtmzWxtczYL2ArQKyuml6BYt9itrAb2MGJFLTyyqooWP2rcrrpoKEYhTj6cXA/b750q+CwXhieQuquy2E4ceDDqk2Z/ysiocnnfAsYiUI6lnDTjnJpGJetcR5zLftnHlYXJVxPwBSt cardno:000604944324

network_interfaces:
- description: Main network
  interface: eth0
  ipv4_address: 10.1.1.3/24
  ipv4_gateway: 10.1.1.1
  ipv6_pd: 0
- description: VPN VLAN
  interface: eth0.4
  ipv4_address: 10.1.4.3/24
  ipv4_gateway: 10.1.4.1
- description: Management VLAN
  interface: eth0.100
network_dns_servers: 10.1.1.1
network_vpn_vlan_interface: "{{ network_interfaces[1].interface }}"
network_vpn_vlan_ipv4_address: "{{ network_interfaces[1].ipv4_address }}"
network_vpn_vlan_ipv4_gateway: "{{ network_interfaces[1].ipv4_gateway }}"
network_vpn_vlan_ipv4_network: "{{ network_vpn_vlan_ipv4_address | ipaddr('subnet') }}"

nfs_mount_path: /mnt/nas/media
nfs_source: 10.1.90.2:/mnt/tank/media
nfs_options: intr

transmission_download: "{{ nfs_mount_path }}/download/Transmission"
transmission_settings:
- key: bind-address-ipv4
  value: "{{ network_vpn_vlan_ipv4_address | ipaddr('address') }}"
- key: bind-address-ipv6
  value: "::1"
- key: download-dir
  value: "{{ transmission_download }}"
- key: incomplete-dir
  value: "{{ transmission_download }}/Incomplete"
- key: peer-port-random-on-start
  value: 'false'
- key: port-forwarding-enabled
  value: 'false'
- key: rpc-authentication-required
  value: 'true'
- key: rpc-password
  value: 'transmission'
- key: rpc-username
  value: transmission
- key: rpc-whitelist
  value: 127.0.0.1,10.1.1.*,94.125.199.30
- key: rpc-whitelist-enabled
  value: 'true'
- key: umask
  value: 2

cloudflare_plex_service_config:
  hostname: plex.synchro.dev
  url: https://localhost:32400
  no-tls-verify: true

cloudflare_transmission_service_config:
  hostname: transmission.synchro.dev
  url: http://localhost:9091

cloudflare_freenas_service_config:
  hostname: freenas.synchro.dev
  url: https://pluto.lan.synchro.dev
  no-tls-verify: true

cloudflare_esxi_service_config:
  hostname: stellar.synchro.dev
  url: https://stellar.lan.synchro.dev
  no-tls-verify: true

cloudflare_ipmi_service_config:
  hostname: stellar-mgmt.synchro.dev
  url: https://stellar.mgmt.synchro.dev
  no-tls-verify: true
