---
- name: Install Binary | build filename of file to be downloaded
  set_fact:
    cloudflared_file: "{{ vars['cloudflared_'+device_arch+'_binary'] }}"

- name: Install Binary | download correct file for device
  get_url:
    url: "{{ cloudflared_base_url }}{{ cloudflared_file }}"
    dest: "/tmp/{{ cloudflared_file }}"

- name: Install Binary | extract cloudflared into /usr/local/bin
  unarchive:
    src: "/tmp/{{ cloudflared_file }}"
    dest: "{{ cloudflared_bin_location }}"
    remote_src: yes
