---
- name: Service | create application user
  user:
    name: cloudflared
    system: yes

- name: Service | create config directory
  file:
    path: /etc/cloudflared
    state: directory
    owner: cloudflared
    group: cloudflared

- name: Service | template config file
  template:
    src: cloudflared.j2
    dest: /etc/default/cloudflared-{{ cloudflared_service_suffix }}
    owner: cloudflared
    group: cloudflared
  notify: restart cloudflared service

- name: Service | template systemd service definition
  template:
    src: cloudflared.service.j2
    dest: /lib/systemd/system/cloudflared-{{ cloudflared_service_suffix }}.service
    owner: root
    group: root
    mode: 0644
  notify: restart cloudflared service
  register: service

- name: Service | enable systemd service
  service:
    name: cloudflared-{{ cloudflared_service_suffix }}
    enabled: "{{ cloudflared_service_enabled }}"
  when: service.changed