---
- name: Service[{{ service_suffix }}] | create application user
  user:
    name: cloudflared
    system: yes
    create_home: no

- name: Service[{{ service_suffix }}] | create config directory
  file:
    path: /etc/cloudflared
    state: directory
    owner: cloudflared
    group: cloudflared

- name: Service[{{ service_suffix }}] | template service config file
  template:
    src: cloudflared.j2
    dest: /etc/default/cloudflared-{{ service_suffix }}
    owner: cloudflared
    group: cloudflared
    mode: 0644
  notify: restart service {{ service_suffix }}

- name: Service[{{ service_suffix }}] | cloudflared config
  copy:
    content: "{{ service_config | to_nice_yaml(indent=2) }}"
    dest: /etc/cloudflared/{{ service_suffix }}.yml
    owner: cloudflared
    group: cloudflared

- name: Service[{{ service_suffix }}] | template service definition
  template:
    src: cloudflared.service.j2
    dest: /lib/systemd/system/cloudflared-{{ service_suffix }}.service
    owner: root
    group: root
    mode: 0644
  notify: 
  - reload systemd
  - restart service {{ service_suffix }}

- name: Service[{{ service_suffix }}] | enable service
  systemd:
    name: cloudflared-{{ service_suffix }}
    enabled: "{{ service_enabled }}"
